### ISSUE TITLE
No rule to make target '/package-defaults.mk

### ISSUE THREAD

**Issue by fuad00** [gngpp/wg-quick#1]
<img width="523" alt="CleanShot 2023-05-17 at 02 04 23@2x" src="https://github.com/gngpp/wg-quick/assets/26776550/16c4e2b7-aecf-4b45-9d8e-970c2700a3af">

Better README.md please!

**Comment by 0x676e67** [comment]
You're operating on OpenWrt? Dude, it needs to be added at compile time

**Comment by 0x676e67** [comment]
You can copy the script content to the system and use it directly，https://git.zx2c4.com/wireguard-tools/tree/src/wg-quick/linux.bash
